### ISSUE TITLE
Crash on 1.18 on the first load

### ISSUE THREAD

**Issue by Hexcede** [Crec0/BetterDarkMode#4]
This mod is crashing on version 1.18 when first loading it. This sounds like an issue reading a config file that doesn't exist yet.

Here is the full error log, deobfuscated by the Not Enough Crashes mod:
```
[23:12:32] [Render thread/ERROR]: Unhandled game exception
java.lang.NullPointerException: Cannot invoke "String.trim()" because "line" is null
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.22) ~[?:?]
	at betterdarkmode.util.Util.readSaveFile(Util.java:53) ~[betterdarkmode-1.0.4.jar:?]
	at betterdarkmode.BetterDarkMode.onLoad(BetterDarkMode.java:26) ~[betterdarkmode-1.0.4.jar:?]
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientLifecycleEvents.lambda$static$0(ClientLifecycleEvents.java:38) ~[fabric-lifecycle-events-v1-1.4.1+713c266865-3d0db15a62b636e6.jar:?]
	at net.minecraft.client.MinecraftClient.handler$zgh000$onStart(MinecraftClient:6508) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:712) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:238) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

**Comment by Crec0** [comment]
Thank you for reporting. Will fix in next release when 1.18.2 drops.
